backend:
  name: github
  repo: Tashimadilrukshi/gatsby-crash-course

media_folder: static/assets
public_folder: assets

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/archive"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: author, label: Author }
      - { name: body, label: Body, widget: markdown }